@api = http://localhost:8080/api

### Samo ime
GET {{api}}/recipes/search?q=kruh

> {%
    client.assert(response.status == 200);
    client.assert(response.body.length >= 1);
%}

### Ime i opis, "+"
GET {{api}}/recipes/search?q=slatki+kruh

> {%
    client.assert(response.status == 200);
    client.assert(response.body.length >= 1);
%}

### Ime i opis, url-encoded razmak
GET {{api}}/recipes/search?q=slatki%20kruh

> {%
    client.assert(response.status == 200);
    client.assert(response.body.length >= 1);
%}


### Ime, opis, kategorija i vrsta kuhinje
GET {{api}}/recipes/search?q=slatki+kruh&category=MainCourse&cuisine=Italian

> {%
    client.assert(response.status == 200);
    client.assert(response.body.length >= 1);
%}

### Kriva kategorija
GET {{api}}/recipes/search?q=slatki+kruh&category=Dessert

> {%
    client.assert(response.status == 200);
    client.assert(response.body.length == 0);
%}

### Tagovi
GET {{api}}/recipes/search?q=kruh&tags=GlutenFree,Vegan

> {%
    client.assert(response.status == 200);
    client.assert(response.body.length >= 1);
%}

### Tagovi, drukčija sintaksa
GET {{api}}/recipes/search?q=kruh&tags=GlutenFree&tags=Vegan

> {%
    client.assert(response.status == 200);
    client.assert(response.body.length >= 1);
%}

### Prazni rezultati
GET {{api}}/recipes/search?q=nePostoji

> {%
    client.assert(response.status == 200);
    client.assert(response.body.length == 0);
%}

### Prazni rezultati - nekorišteni tagovi
GET {{api}}/recipes/search?tags=Lent

> {%
    client.assert(response.status == 200);
    client.assert(response.body.length == 0);
%}

### Samo kategorija
GET {{api}}/recipes/search?category=MainCourse

> {%
    client.assert(response.status == 200);
    client.assert(response.body.length >= 1);
%}
